version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instamitra
    volumes:
      - mysql_data:/var/lib/mysql   # ✅ Persistent volume
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7.0
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s

  service-registry:
    build: ./Service-Registry
    image: service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - backend

  admin-server-app:
    build: ./Admin-Server-App
    image: admin-server-app:latest
    container_name: admin-server-app
    ports:
      - "9090:8080"
    networks:
      - backend
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/

  api-gateway:
    build: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - admin-server-app
      - mysql
      - redis
    networks:
      - backend
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server-app:8080
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379

  admin-service:
    build: ./Admin-service
    image: admin-service:latest
    container_name: admin-service
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/instamitra
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server-app:8080
      SUPER_ADMIN_NUMBER: 1234567890
      SUPER_ADMIN_KEY: mySuperSecretKey

  user-service:
    build: ./User-Service
    image: user-service:latest
    container_name: user-service
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/instamitra
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server-app:8080

  provider-service:
    build: ./Provider-Service
    image: provider-service:latest
    container_name: provider-service
    ports:
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/instamitra
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server-app:8080

  payment-service:
    build: ./Payment-Service
    image: payment-service:latest
    container_name: payment-service
    ports:
      - "8084:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/instamitra
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server-app:8080

  service-catalog-service:
    build: ./service-catalog-service
    image: service-catalog-service:latest
    container_name: service-catalog-service
    ports:
      - "8085:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/instamitra
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server-app:8080

  orders-service:
    build: ./Orders-Service
    image: orders-service:latest
    container_name: orders-service
    ports:
      - "8086:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/instamitra
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_BOOT_ADMIN_CLIENT_URL: http://admin-server-app:8080

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
