eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

order:
  base-url: http://order-service:8086

spring:
  application:
    name: orders-service
  boot:
    admin:
      client:
        url: http://spring-boot-admin:9090
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin123
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html



resilience4j:
  retry:
    instances:
      orderServiceRetry:
        maxAttempts: 3
        waitDuration: 2s

  circuitbreaker:
    instances:
      orderServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s


logging:
  level:
    org.springframework.boot.devtools.restart: INFO
    io.github.resilience4j: INFO
