
spring:
  application:
    name: service-catalog-service
  boot:
    admin:
      client:
        url: http://admin-server-app:8080
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin123



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    instance:
      prefer-ip-address: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
