
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

order:
  base-url: http://localhost:8082

spring:
  application:
    name: provider-service

  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin123


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


resilience4j:
  retry:
    instances:
      providerServiceRetry:
        maxAttempts: 3
        waitDuration: 2s

  circuitbreaker:
    instances:
      providerServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
