apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: instamitra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: <account-id>.dkr.ecr.<region>.amazonaws.com/instamitra-ci-admin-service:v1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/instamitra
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka/
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://admin-server-app:8080
            - name: SUPER_ADMIN_NUMBER
              value: "1234567890"
            - name: SUPER_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: super-key
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: instamitra
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - port: 8080
      targetPort: 8080
