apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: instamitra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: instamitra-ci-orders-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/instamitra
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka/
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://admin-server-app:8080
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: instamitra
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
    - port: 8080
      targetPort: 8080
