apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-service
  namespace: instamitra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider-service
  template:
    metadata:
      labels:
        app: provider-service
    spec:
      containers:
        - name: provider-service
          image: 087725326648.dkr.ecr.ap-south-1.amazonaws.com/instamitra-ci-provider-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mysql-secret
            - configMapRef:
                name: provider-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: provider-service
  namespace: instamitra
spec:
  type: ClusterIP
  selector:
    app: provider-service
  ports:
    - port: 8080
      targetPort: 8080
