apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalog-service
  namespace: instamitra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-catalog-service
  template:
    metadata:
      labels:
        app: service-catalog-service
    spec:
      containers:
        - name: service-catalog-service
          image: 087725326648.dkr.ecr.ap-south-1.amazonaws.com/instamitra/service-catalog-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/instamitra
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka/
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://admin-server-app:8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-catalog-service
  namespace: instamitra
spec:
  type: ClusterIP
  selector:
    app: service-catalog-service
  ports:
    - port: 8080
      targetPort: 8080
