eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: payment-service
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          prefer-ip: true
          metadata:
            user.name: admin
            user.password: admin123

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html



