
spring:
  application:
    name: admin-server-app
  boot:
    admin:
      ui:
        title: "Admin Dashboard"
      discovery:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    instance:
      prefer-ip-address: true
