server:
  port: 9090

spring:
  application:
    name: admin-server-app
  boot:
    admin:
      ui:
        title: "Admin Dashboard"
      discovery:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.2
